<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  server-el7:
    roles:
      - default
      - server
    masterless: true
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 2048
    vagrant_cpus: 2
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt
  client-el7:
    roles:
      - client
    masterless: true
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt
  client-el6:
    roles:
      - client
      - no_fips
    masterless: true
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/0608B895.txt
  client-oel6:
    roles:
      - client
      - no_fips
    masterless: true
    platform:   el-6-x86_64
    box:        onyxpoint/oel-6-x86_64
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/0608B895.txt
  client-oel7:
    roles:
      - client
    masterless: true
    platform:   el-7-x86_64
    box:        onyxpoint/oel-7-x86_64
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt

CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
  vagrant_cpus: 1
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
